name: shop_sphere
description: "E-commerce flutter application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0


flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
     - family: DM-sans
       fonts:
         - asset: assets/fonts/dm-sans/DMSans-Thin.ttf
           weight: 100
           style: normal
         - asset: assets/fonts/dm-sans/DMSans-ThinItalic.ttf
           weight: 100
           style: italic
         - asset: assets/fonts/dm-sans/DMSans-ExtraLight.ttf
           weight: 200
           style: normal
         - asset: assets/fonts/dm-sans/DMSans-ExtraLightItalic.ttf
           weight: 200
           style: italic
         - asset: assets/fonts/dm-sans/DMSans-Light.ttf
           weight: 300
           style: normal
         - asset: assets/fonts/dm-sans/DMSans-LightItalic.ttf
           weight: 300
           style: italic
         - asset: assets/fonts/dm-sans/DMSans-Regular.ttf
           weight: 400
           style: normal
         - asset: assets/fonts/dm-sans/DMSans-Italic.ttf
           weight: 400
           style: italic
         - asset: assets/fonts/dm-sans/DMSans-Medium.ttf
           weight: 500
           style: normal
         - asset: assets/fonts/dm-sans/DMSans-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/fonts/dm-sans/DMSans-SemiBold.ttf
           weight: 600
           style: normal
         - asset: assets/fonts/dm-sans/DMSans-SemiBoldItalic.ttf
           weight: 600
           style: italic
         - asset: assets/fonts/dm-sans/DMSans-Bold.ttf
           weight: 700
           style: normal
         - asset: assets/fonts/dm-sans/DMSans-BoldItalic.ttf
           weight: 700
           style: italic
         - asset: assets/fonts/dm-sans/DMSans-ExtraBold.ttf
           weight: 800
           style: normal
         - asset: assets/fonts/dm-sans/DMSans-ExtraBoldItalic.ttf
           weight: 800
           style: italic
         - asset: assets/fonts/dm-sans/DMSans-Black.ttf
           weight: 900
           style: normal
         - asset: assets/fonts/dm-sans/DMSans-BlackItalic.ttf
           weight: 900
           style: italic